export const CREATE_ORDER_PAYMENT_REQUEST = "CREATE_ORDER_PAYMENT_REQUEST"
export const CREATE_ORDER_PAYMENT_FAILURE = "CREATE_ORDER_PAYMENT_FAILURE"
export const CREATE_ORDER_PAYMENT_SUCCESS = "CREATE_ORDER_PAYMENT_SUCCESS"

export const UPDATE_ORDER_PAYMENT_REQUEST = "UPDATE_ORDER_PAYMENT_REQUEST"
export const UPDATE_ORDER_PAYMENT_FAILURE = "UPDATE_ORDER_PAYMENT_FAILURE"
export const UPDATE_ORDER_PAYMENT_SUCCESS = "UPDATE_ORDER_PAYMENT_SUCCESS"
