export const ADD_ITEM_TO_CART_REQUEST = "ADD_ITEM_TO_CART_REQUEST ";
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS";
export const ADD_ITEM_TO_CART_FAILURE = "ADD_ITEM_TO_CART_FAILURE";

export const GET_ITEM_TO_CART_REQUEST= "GET_ITEM_TO_CART_REQUEST";
export const GET_ITEM_TO_CART_SUCCESS = "GET_ITEM_TO_CART_SUCCESS";
export const GET_ITEM_TO_CART_FAILURE = "GET_ITEM_TO_CART_FAILURE";

export const REMOVE_ITEM_TO_CART_REQUEST = "REMOVE_ITEM_TO_CART_REQUEST";
export const REMOVE_ITEM_TO_CART_SUCCESS = "REMOVE_ITEM_TO_CART_SUCCESS";
export const REMOVE_ITEM_TO_CART_FAILURE = "REMOVE_ITEM_TO_CART_FAILURE";

export const UPDATE_ITEM_TO_CART_REQUEST = "UPDATE_ITEM_TO_CART_REQUEST";
export const UPDATE_ITEM_TO_CART_SUCCESS = "UPDATE_ITEM_TO_CART_SUCCESS";
export const UPDATE_ITEM_TO_CART_FAILURE = "UPDATE_ITEM_TO_CART_FAILURE";

export const CREATE_CART_FOR_USER_REQUEST = "CREATE_CART_FOR_USER_REQUEST";
export const CREATE_CART_FOR_USER_SUCCESS = "CREATE_CART_FOR_USER_SUCCESS";
export const CREATE_CART_FOR_USER_FAILURE = "CREATE_CART_FOR_USER_FAILURE";